export const neighborhoods = [
  {
    id: 1,
    name: 'Alto Alegre',
    description: 'Área residencial em desenvolvimento',
    status: 'operational',
    reports: 3,
  },
  {
    id: 2,
    name: 'Área Nobre',
    description: 'Região residencial de alto padrão',
    status: 'operational',
    reports: 1,
  },
  {
    id: 3,
    name: 'Boa Vista',
    description: 'Bairro residencial tradicional',
    status: 'warning',
    reports: 8,
  },
  {
    id: 4,
    name: 'Cacimbas',
    description: 'Área residencial histórica',
    status: 'operational',
    reports: 2,
  },
  {
    id: 5,
    name: 'Centro',
    description: 'Distrito comercial principal',
    status: 'warning',
    reports: 15,
  },
  {
    id: 6,
    name: 'Conjunto COHAB',
    description: 'Conjunto habitacional',
    status: 'critical',
    reports: 32,
  },
  {
    id: 7,
    name: 'Coqueiro',
    description: 'Área residencial arborizada',
    status: 'operational',
    reports: 4,
  },
  {
    id: 8,
    name: 'Cruzeiro',
    description: 'Área mista residencial e comercial',
    status: 'warning',
    reports: 12,
  },
  {
    id: 9,
    name: 'Das Flores',
    description: 'Bairro residencial familiar',
    status: 'operational',
    reports: 1,
  },
  {
    id: 10,
    name: 'Estação',
    description: 'Região da estação ferroviária',
    status: 'operational',
    reports: 0,
  },
  {
    id: 11,
    name: 'Fazendinha',
    description: 'Área residencial suburbana',
    status: 'warning',
    reports: 7,
  },
  {
    id: 12,
    name: 'Julho',
    description: 'Bairro residencial em expansão',
    status: 'operational',
    reports: 2,
  },
  {
    id: 13,
    name: 'Ladeira',
    description: 'Área residencial tradicional',
    status: 'warning',
    reports: 9,
  },
  {
    id: 14,
    name: 'Madalenas',
    description: 'Bairro residencial consolidado',
    status: 'critical',
    reports: 28,
  },
  {
    id: 15,
    name: 'Maranhão',
    description: 'Área residencial popular',
    status: 'operational',
    reports: 5,
  },
  {
    id: 16,
    name: 'Mourão',
    description: 'Bairro residencial tranquilo',
    status: 'operational',
    reports: 1,
  },
  {
    id: 17,
    name: 'Nova Aldeota',
    description: 'Área residencial moderna',
    status: 'warning',
    reports: 11,
  },
  {
    id: 18,
    name: 'Picos',
    description: 'Região comercial e residencial',
    status: 'operational',
    reports: 3,
  },
  {
    id: 19,
    name: 'São Francisco',
    description: 'Bairro residencial familiar',
    status: 'warning',
    reports: 14,
  },
  {
    id: 20,
    name: 'São Sebastião',
    description: 'Área residencial tradicional',
    status: 'operational',
    reports: 2,
  },
  {
    id: 21,
    name: 'Senharão',
    description: 'Bairro residencial histórico',
    status: 'warning',
    reports: 6,
  },
  {
    id: 22,
    name: 'Violete',
    description: 'Área residencial em desenvolvimento',
    status: 'operational',
    reports: 4,
  },
];